name: Release Builds
on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/*'

jobs:
  # >>>>>>> Android build <<<<<<< #
  maui-android:
    runs-on: windows-2022
    steps:
      - uses: ./releases/android-release.yml

  # >>>>>>> Windows Build <<<<<<< #
  maui-windows:
    runs-on: windows-2022
    steps:
      - uses: ./releases/windows-release.yml

  # iOS and MacOS builds are ideally built on your own self-hosted runner, because a valid keychain can already be installed.
  # It is possible to install your provisioningprofile and certificate on a Microsoft-hosted runner, but outside the scope of this demo
  # >>>>>>> iOS Build <<<<<<< #
  maui-ios:
    runs-on: macos-12
    steps:
      - uses: ./releases/ios-release.yml

  # >>>>>>> MacCatalyst Build <<<<<<< #
  maui-macos:
    runs-on: macos-12
    steps:
      - uses: ./releases/maccatalyst-release.yml
    