name: Release Builds
on:
  # Allow a manual trigger, just in case.
  workflow_dispatch:
  push:
    branches:
      - 'releases'
    paths:
      - 'src/MauiDemo/**/*'
      - '.github/workflows/releases.yml'

env:
  PROJECT_PATH: "src/MauiDemo/MauiDemo.csproj"
  BUILD_CONFIGURATION: Release

jobs:
# ********************************************************************** #
#                            Android
# ********************************************************************** #

  android-release:
    runs-on: windows-2022
    env:
      TFM: net8.0-android
      ARTIFACTS_PATH: "artifacts_android"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: '11'
    
    - name: Install MAUI workloads
      run: dotnet workload install maui --source "https://api.nuget.org/v3/index.json"
    
    - name: Decode the Keystore into File
      run: |
        $file_bytes = [System.Convert]::FromBase64String("${{secrets.ANDROID_SIGNING_KEYSTORE_BASE64}}")
        [IO.File]::WriteAllBytes("${{github.workspace}}/${{secrets.ANDROID_SIGNING_KEYSTORE_FILENAME}}", $file_bytes)

    # Docs https://learn.microsoft.com/en-us/dotnet/maui/android/deployment/publish-cli?view=net-maui-8.0
    - name: Build MAUI Android project
      run: dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIGURATION}} -f ${{env.TFM}} -p:AndroidKeyStore=true -p:AndroidSigningKeyStore="${{github.workspace}}/${{secrets.ANDROID_SIGNING_KEYSTORE_FILENAME}}" -p:AndroidSigningStorePass="${{secrets.ANDROID_SIGNING_STORE_PASS}}" -p:AndroidSigningKeyAlias="${{secrets.ANDROID_SIGNING_KEY_ALIAS}}" -p:AndroidSigningKeyPass="${{secrets.ANDROID_SIGNING_KEY_PASS}}"

    # Upload the artifact the Action's result
    # To publish to the store, see https://github.com/marketplace/actions/upload-android-release-to-play-store
    - name: Upload Android artifacts (APKs & AABs)
      uses: actions/upload-artifact@v4
      with:
        name: "Android Artifacts" 
        path: "${{github.workspace}}/**/*Signed.a*"
        if-no-files-found: warn
        retention-days: 10


# ********************************************************************** #
#                            Windows
# ********************************************************************** #

  windows-release:
    runs-on: windows-2022
    env:
      TFM: net8.0-windows10.0.19041.0
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui --source "https://api.nuget.org/v3/index.json"

    # Option A (normal) Import your PFX
    # - name: Base64 To PFX file
    #   id: write_file
    #   uses: timheuer/base64-to-file@v1.2
    #   with:
    #     fileName: "${{ secrets.CODESIGN_CERTIFICATE_FILENAME }}"
    #     fileDir: "${{github.workspace}}"
    #     encodedString: ${{ secrets.CODESIGN_CERTIFICATE_BASE64 }}
    
    # Option B (only for this demo) Generating a self-signed certificate to codesign with
    - name: Create Codesigning Cert
      id: certgen
      run: |
        # Normally you would import your own cert here (see https://github.com/marketplace/actions/base64-to-file).
        $cert = New-SelfSignedCertificate -Type Custom -Subject "CN=LancelotTemp" -KeyUsage DigitalSignature -FriendlyName "LancelotTemp" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
        $thumb=$cert.Thumbprint
        echo "thumbprint=$thumb" >> "$ENV:GITHUB_OUTPUT"
    
    # Docs https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli?view=net-maui-8.0
    - name: Build Maui WinUI project
      run: |
        dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIGURATION}} -f ${{env.TFM}} -p:RuntimeIdentifierOverride=win10-x64 -p:PublishTrimmed=False -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateThumbprint=${{steps.certgen.outputs.thumbprint}}

        # In the real world, you would use Option A, so you'd also use these build parameters instead.
        # -p:PackageCertificateKeyFile="${{steps.write_file.outputs.filePath}}" -p:PackageCertificatePassword="${{secrets.CODESIGN_CERTIFICATE_PASSWORD}}"

    # Upload the artifact the Action's result
    # To publish to the stopre, see https://github.com/marketplace/actions/microsoft-store-publish
    - name: Upload WinUI artifacts
      uses: actions/upload-artifact@v4
      with:     
        name: "WINUI Artifacts" 
        path: "${{github.workspace}}/**/*.msix"
        if-no-files-found: warn
        retention-days: 10


# ********************************************************************** #
#                               iOS
# ********************************************************************** #

  ios-release:
    runs-on: macos-14
    env:
      TFM: net8.0-ios
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui --source "https://api.nuget.org/v3/index.json"

    # Docs https://github.com/Apple-Actions/import-codesign-certs
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: "${{secrets.APPLE_DISTRIBUTION_CERT_BASE64}}"
        p12-password: "${{secrets.APPLE_DISTRIBUTION_CERT_PASSWORD}}"

    # Docs https://github.com/Apple-Actions/download-provisioning-profiles
    - uses: Apple-Actions/download-provisioning-profiles@v2
      with:
        profile-type: "IOS_APP_STORE"
        bundle-id: "MauiDemo"
        issuer-id: "${{secrets.APPSTORE_API_ISSUER_ID}}"
        api-key-id: "${{secrets.APPSTORE_API_KEY_ID}}"
        api-private-key: "${{secrets.APPSTORE_API_PRIVATE_KEY}}"

    # Docs https://learn.microsoft.com/en-us/dotnet/maui/ios/deployment/publish-cli?view=net-maui-8.0
    - name: Build MAUI iOS project
      run: |
        dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIGURATION}} -f ${{env.TFM}} -p:RuntimeIdentifier=ios-arm64 -p:PublishTrimmed=true -p:MtouchLink=SdkOnly -p:ApplicationId=MauiDemo -p:CodesignProvision=MauiDemo -p:CodesignKey="Apple Distribution: Lancelot Software, LLC (L65255N3F7)"

    # # Docs https://github.com/Apple-Actions/upload-testflight-build
    # - name: 'Upload app to TestFlight'
    #   uses: apple-actions/upload-testflight-build@v1
    #   with: 
    #     app-path: "${{github.workspace}}/**/*.ipa" 
    #     issuer-id: ${{secrets.APPSTORE_API_ISSUER_ID}}
    #     api-key-id: "${{secrets.APPSTORE_API_KEY_ID}}"
    #     api-private-key: "${{secrets.APPSTORE_API_PRIVATE_KEY}}"

    # Upload the artifact the Action's result
    - name: Upload iOS artifacts
      uses: actions/upload-artifact@v4
      with:     
        name: "iOS artifacts" 
        path: "${{github.workspace}}/**/*.ipa"
        if-no-files-found: warn
        retention-days: 10


# ********************************************************************** #
#                         MacCatalyst
# ********************************************************************** #

  maccatalyst-release:
    runs-on: macos-14
    env:
      TFM: net8.0-maccatalyst
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI workloads
      run: dotnet workload install maui --source "https://api.nuget.org/v3/index.json"

    # Docs https://github.com/Apple-Actions/import-codesign-certs
    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v2
      with:
        p12-file-base64: "${{secrets.APPLE_DISTRIBUTION_CERT_BASE64}}"
        p12-password: "${{secrets.APPLE_DISTRIBUTION_CERT_PASSWORD}}"

    # Docs https://github.com/Apple-Actions/download-provisioning-profiles
    - uses: Apple-Actions/download-provisioning-profiles@v2
      with:
        profile-type: "MAC_APP_STORE"
        bundle-id: "com.lancelotsoftware.MauiDemo"
        issuer-id: "${{secrets.APPSTORE_API_ISSUER_ID}}"
        api-key-id: "${{secrets.APPSTORE_API_KEY_ID}}"
        api-private-key: "${{secrets.APPSTORE_API_PRIVATE_KEY}}"

    # Docs https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/deployment/publish-app-store?view=net-maui-8.0 (carefully follow the intructions about entitlements.plist and info.plist)
    - name: Build MAUI MacCatalyst project
      run: |
        dotnet publish ${{env.PROJECT_PATH}} -c ${{env.BUILD_CONFIGURATION}} -f ${{env.TFM}} -p:RuntimeIdentifier=maccatalyst-x64 -p:EnableCodeSigning=true -p:EnablePackageSigning=true -p:PublishTrimmed=true -p:MtouchLink=SdkOnly -p:ApplicationId=com.lancelotsoftware.MauiDemo -p:CodesignProvision=MauiDemo -p:CodesignKey="Apple Distribution: Lancelot Software, LLC (L65255N3F7)" -p:CodesignEntitlements='Platforms\MacCatalyst\Entitlements.plist'

    # # Docs https://github.com/Apple-Actions/upload-testflight-build
    # - name: 'Upload app to TestFlight'
    #   uses: apple-actions/upload-testflight-build@v1
    #   with: 
    #     app-path: "${{github.workspace}}/**/*.pkg" 
    #     issuer-id: ${{secrets.APPSTORE_API_ISSUER_ID}}
    #     api-key-id: "${{secrets.APPSTORE_API_KEY_ID}}"
    #     api-private-key: "${{secrets.APPSTORE_API_PRIVATE_KEY}}"

    # Upload the artifact the Action's result
    - name: Upload maccatalyst artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "maccatalyst artifacts" 
        path: "${{github.workspace}}/**/*.pkg"
        if-no-files-found: warn
        retention-days: 10
    